CREATE TABLE IF NOT EXISTS `liloo_orders` (
  `order_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `order_code` varchar(150) NOT NULL COMMENT 'Código do pedido',
  `order_account_id` bigint(20) DEFAULT NULL COMMENT 'ID do usuário da conta',
  `order_client_id` bigint(20) DEFAULT NULL COMMENT 'ID do cliente na tb liloo_clients',
  `order_client_code` varchar(50) DEFAULT NULL COMMENT 'Código do Cliente (Opção assim com o ID)',
  `order_description` longtext COMMENT 'Descrição ou observações gerais do pedido',
  `order_delivery` varchar(150) DEFAULT NULL COMMENT 'Detalhes da entrega',
  `order_pay_method` varchar(150) DEFAULT NULL COMMENT 'Método e pegamento. Se cartão, boleto, pix e etc.',
  `order_pay_frequency` varchar(150) DEFAULT NULL COMMENT 'Periodicidade do pagemento em casos de recorrencia',
  `order_pay_day` varchar(50) DEFAULT NULL COMMENT 'Dia do pagamento em casos de Parcelamento',
  `order_pay_parcel` int(11) DEFAULT NULL COMMENT 'Número de parcelas',
  `order_pay_conditions` longtext COMMENT 'Condições de pagamento (Descrição)',
  `order_price_total` float(10,2) DEFAULT NULL COMMENT 'Valor Total do Pedido',
  `order_price_discount` float DEFAULT NULL COMMENT 'Percentual de Desconto. Ex.: 5%, 7,2% e etc',
  `order_status` varchar(150) DEFAULT NULL COMMENT 'Acompanhamento do pedido. Se aberto, finalizado e etc.',
  `order_validity` datetime DEFAULT NULL COMMENT 'Validade do Pedido',
  `order_registered` datetime DEFAULT CURRENT_TIMESTAMP,
  `order_modify` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`order_id`),
  UNIQUE KEY `order_code` (`order_code`),
  KEY `FK_liloo_orders_liloo_clients` (`order_client_id`),
  KEY `FK_liloo_orders_liloo_accounts` (`order_account_id`),
  CONSTRAINT `FK_liloo_orders_liloo_accounts` FOREIGN KEY (`order_account_id`) REFERENCES `liloo_accounts` (`account_id`),
  CONSTRAINT `FK_liloo_orders_liloo_clients` FOREIGN KEY (`order_client_id`) REFERENCES `liloo_clients` (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;