<?php

$TOKEN = 'EAAtnNnObyGYBAOQE3ZB1ZB5NUNxYZCk4E1OZCDaHgd0VoxMFXi1OurOpyF1UGpPHZA3ds3nnOiSoxq9BStvhJsMItAGfzEgIfoLvLbBfjRUWzLCw84Q3gRfZBxZA5nr17qZBa8NgdPRJ1Sjtc0jrZB7dZAl3nb8fAaHEi7fPMhCgPZBiijLM4ZCR2kwt6ZCVYpUFSSagm0x8V9M9COCUt0NerTefpRcMzqjZAEOUUZD';

// curl -i -X POST `
//   https://graph.facebook.com/v13.0/106242535430409/messages `
//   -H 'Authorization: Bearer EAAtnNnObyGYBAOQE3ZB1ZB5NUNxYZCk4E1OZCDaHgd0VoxMFXi1OurOpyF1UGpPHZA3ds3nnOiSoxq9BStvhJsMItAGfzEgIfoLvLbBfjRUWzLCw84Q3gRfZBxZA5nr17qZBa8NgdPRJ1Sjtc0jrZB7dZAl3nb8fAaHEi7fPMhCgPZBiijLM4ZCR2kwt6ZCVYpUFSSagm0x8V9M9COCUt0NerTefpRcMzqjZAEOUUZD' `
//   -H 'Content-Type: application/json' `
//   -d '{ \"messaging_product\": \"whatsapp\", \"to\": \"5513981750225\", \"type\": \"template\", \"template\": { \"name\": \"hello_world\", \"language\": { \"code\": \"en_US\" } } }'

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
// $ch = curl_init();

// curl_setopt($ch, CURLOPT_URL, 'https://graph.facebook.com/v13.0/5513981750195/messages');
// curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
// curl_setopt($ch, CURLOPT_POST, 1);
// curl_setopt($ch, CURLOPT_POSTFIELDS, "{ 
//     \"messaging_product\": \"whatsapp\", 
//     \"to\": \"5513981750225\", 
//     \"type\": \"template\", 
//     \"template\": { 
//         \"name\": \"hello_world\", 
//         \"language\": { \"code\": \"en_US\" }
//     }
// }");

// $headers = array();
// $headers[] = 'Authorization: Bearer EAAtnNnObyGYBACBxn8gHESnHtP6vftuBPw7N6VLwlCqlNqaISXsu7P0F5tmOwpPU6r5kwhLfMrPe7fhUwDqZAuJ1KzSJNrIwS3ZCqLl65zFZBrM6HkgsJjj3LT363E6MRdFc4CWKOYXbDJRM7cvZBbKRSy7o8e7vYR94zablO9MvXjN0cnHk2UdZBEiLpveQIaKGhZCHOJGAZDZD';
// $headers[] = 'Content-Type: application/json';
// curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

// $result = curl_exec($ch);
// if (curl_errno($ch)) {
//     echo 'Error:' . curl_error($ch);
// }
// curl_close($ch);